name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*.*.*'  # triggers only on semver tags like v1.0.0, v2.3.4, etc.

permissions:
  contents: read
  packages: write  # needed for pushing to ghcr.io
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag version
        id: extract_version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "version=${TAG#v}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ steps.extract_version.outputs.version }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ steps.extract_version.outputs.version }}
