name: Build and Push Docker Image

# on:
#   push:
#     tags:
#       - 'v*'  # triggers only on semver tags like v1.0.0, v2.3.4, etc.

on:
  push:
    tags:
      - "*"
    # branches:
    #   - main

permissions:
  contents: read
  packages: write  # needed for pushing to ghcr.io
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Normalize repository name
        id: repo
        run: |
          repo_lower=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "repo=$repo_lower" >> $GITHUB_OUTPUT

      - name: Extract tag version
        id: version
        run: |
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build image
        run: |
          docker build -t ghcr.io/${{ steps.repo.outputs.repo }}:${{ steps.version.outputs.version }} .

      - name: Push image
        run: |
          docker push ghcr.io/${{ steps.repo.outputs.repo }}:${{ steps.version.outputs.version }}

