name: Docker Build & Push (from package.json)

on:
  workflow_dispatch:  # You trigger this manually or from another workflow

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Normalize repository name (lowercase)
        id: repo
        run: |
          repo_lower=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "repo=$repo_lower" >> $GITHUB_OUTPUT

      - name: Read version from package.json
        id: version
        run: |
          version=$(jq -r .version package.json)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ steps.repo.outputs.repo }}:${{ steps.version.outputs.version }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ steps.repo.outputs.repo }}:${{ steps.version.outputs.version }}
