name: Tag Release from Conventional Commits

on:
  push:
    branches:
      - main

permissions:
  contents: write  # required to push a tag

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install standard-version
        run: |
          npm install --save-dev standard-version

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version and create tag
        run: |
          npx standard-version

      - name: Push tag and changelog
        run: |
          git push --follow-tags origin main

          - name: Trigger Docker Publish Workflow

      - name: Trigger Docker Publish Workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/docker-publish.yml/dispatches \
            -d '{"ref":"main"}'
