name: Universal Airgapper

on:
  workflow_call:
    inputs:
      job-name:
        description: 'Job Name'
        default: 'airgapper'
        required: false
        type: string
      image_registry:
        description: 'Registry of the image to use'
        default: 'ghcr.io'
        required: false
        type: string
      image_name:
        description: 'Name of the image'
        default: 'fullstacks-gmbh/universal-airgapper'
        required: false
        type: string
      image_tag:
        description: 'Tag of the image'
        default: '0.0.10'
        required: false
        type: string
      image_pull_policy:
        description: 'Image pull policy'
        default: 'always'
        required: false
        type: string
      config-folder:
        description: '--config-folder parameter; path to folder, containing config files'
        required: false
        type: string
      debug:
        description: 'Enable debug mode'
        default: ''
        required: false
        type: string
      credentials-secret-name:
        description: 'Name of the secret containing the credentials'
        default: 'UNIVERSAL_AIRGAPPER_CREDS'
        required: false
        type: string

jobs:
  airgapper:
    name: ${{ inputs.job-name || 'airgapper' }}
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image_registry || 'registry.lab.cloudstacks.eu' }}/${{ inputs.image_name || 'fullstacks-tools/universal-airgapper' }}:${{ inputs.image_tag || 'latest' }}
      options: --pull=${{ inputs.image_pull_policy || 'always' }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show config files
        run: |
          CONFIG_FOLDER="${{ inputs.config-folder }}"
          if [ -z "$CONFIG_FOLDER" ]; then CONFIG_FOLDER="${GITHUB_WORKSPACE}"; fi
          echo "========================================================"
          echo "================ Universal Airgapper [ $APP_VERSION ] ============"
          echo "================ Commit - $APP_COMMIT_SHA  ==================="
          echo "====================== CONFIG =========================="
          cat "$CONFIG_FOLDER"/*.yaml || true
          echo "========================================================"

      - name: Write credentials file
        run: echo "${{ secrets[inputs.credentials-secret-name] }}" > credentials.yaml

      - name: Run Universal Airgapper
        run: |
          python /home/airgapper/main.py \
            --credentials-file "credentials.yaml" \
            --config-folder "${{ inputs.config-folder || github.workspace }}" ${{ inputs.debug }}